# FROM ubuntu:latest

# RUN apt-get update && apt-get install -y sudo ntp ntpdate ntpstat traceroute

# # give everyone sudo access

# RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# # Create a user
# RUN adduser --disabled-password --gecos "" davezczesny

# RUN mkdir -p /home/davezczesny/ntp_data
# RUN touch /home/davezczesny/ntp_data/ntp_data.csv

# RUN mkdir -p /home/davezczesny/ntp_data && \
#     touch /home/davezczesny/ntp_data/ntp_data.csv && \
#     sudo chown -R davezczesny:davezczesny /home/davezczesny && \
#     sudo chmod -R 777 /home/davezczesny



# COPY ntp_data.sh /home/davezczesny/ntp_data.sh
# RUN sudo chmod +x /home/davezczesny/ntp_data.sh

# COPY entrypoint.sh /home/davezczesny/entrypoint.sh
# RUN sudo chmod +x /home/davezczesny/entrypoint.sh

# # give write permissions

# WORKDIR /home/davezczesny

# RUN sudo chmod -R 777 /home/davezczesny/ntp_data
# # Switch to the user
# USER davezczesny

# # RUN sudo ntpd -gq &

# # verify ntp status

# # RUN ntpq -p


# # CMD ["/bin/bash"]
# # CMD sudo ntpd -gq && ./ntp_data.sh
# CMD ["/home/davezczesny/entrypoint.sh"]


FROM ubuntu:latest

RUN apt-get update && apt-get install -y sudo ntp ntpdate ntpstat traceroute

# Give everyone sudo access (optional, if you need it)
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


# Copy the scripts
COPY ntp_data.sh /home/davezczesny/ntp_data.sh
RUN chmod +x /home/davezczesny/ntp_data.sh

COPY entrypoint.sh /home/davezczesny/entrypoint.sh
RUN chmod +x /home/davezczesny/entrypoint.sh


RUN mkdir -p /home/davezczesny/ntp
RUN touch /home/davezczesny/ntp/ntp_info.csv

RUN sudo chmod -R 777 /home/davezczesny/ntp

# verify that /ntp and /ntp/ntp_info.csv exists
RUN ls -la /home/davezczesny/ntp
RUN ls -la /home/davezczesny/ntp/ntp_info.csv

# Set working directory
WORKDIR /home/davezczesny

# Default command
CMD ["/home/davezczesny/entrypoint.sh"]